### ISSUE TITLE
Encoding error when exporting data

### ISSUE THREAD

**Issue by Jerry-kiwi** [boundlessgeo/qgis-geoserver-plugin#106]
QGIS 3.4
Geoserver 12.4.1
Latest  plugin (copied from git)
I have attributes in utf8 and get error while export to geoserver

Geoserver: 'latin-1' codec can't encode characters in position

**Comment by Jerry-kiwi** [comment]
`2019-01-06T13:33:29     CRITICAL    'latin-1' codec can't encode characters in position 13-19: Body ('Автобус') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.:Traceback (most recent call last):
              File "/home/www_adm/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/gui/gsoperations.py", line 40, in run
              catalog.publishLayer(*layerAndParams)
              File "/home/www_adm/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/qgis/catalog.py", line 281, in publishLayer
              sld = self.publishStyle(layer, overwrite, name) if style is None else None
              File "/home/www_adm/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/qgis/catalog.py", line 140, in publishStyle
              self.catalog.create_style(name, sld, overwrite)
              File "/home/www_adm/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/extlibs/geoserver/catalog.py", line 974, in create_style
              resp = self.http_request(style.create_href, method='post', data=xml, headers=headers)
              File "/home/www_adm/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/extlibs/geoserver/catalog.py", line 139, in http_request
              resp = req_method(url, headers=headers, data=data, auth=(self.username, self.password))
              File "/usr/lib/python3/dist-packages/requests/sessions.py", line 567, in post
              return self.request('POST', url, data=data, json=json, **kwargs)
              File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
              resp = self.send(prep, **send_kwargs)
              File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
              r = adapter.send(request, **kwargs)
              File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
              timeout=timeout
              File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
              chunked=chunked)
              File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
              conn.request(method, url, **httplib_request_kw)
              File "/usr/lib/python3.6/http/client.py", line 1239, in request
              self._send_request(method, url, body, headers, encode_chunked)
              File "/usr/lib/python3.6/http/client.py", line 1284, in _send_request
              body = _encode(body, 'body')
              File "/usr/lib/python3.6/http/client.py", line 161, in _encode
              (name.title(), data[err.start:err.end], name)) from None
             UnicodeEncodeError: 'latin-1' codec can't encode characters in position 13-19: Body ('Автобус') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.`
