### ISSUE TITLE
Drag&Drop from browser to a nod different to workspace stuck qgis

### ISSUE THREAD

**Issue by luipir** [boundlessgeo/qgis-geoserver-plugin#17]
If I drag &drop a layer from browser to a plugin node that is not a workspace, the plugin start something that stuck qgis (qgis is greyed)

it's possibile to reset it doing ctrl-c in terminal (if qgis is run from terminal)...in this case the log message is:

^CTraceback (most recent call last):
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/gui/explorertree.py", line 214, in dropEvent
    toUpdate = destinationItem.acceptDroppedUris(self, self.explorer, elements)
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 393, in acceptDroppedUris
    return addDraggedUrisToWorkspace(uris, self.parentCatalog(), self.getDefaultWorkspace(), explorer, tree)
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 74, in getDefaultWorkspace
    workspaces = self.parentCatalog().get_workspaces()
  File "build/bdist.linux-x86_64/egg/geoserver/catalog.py", line 861, in get_workspaces
  File "build/bdist.linux-x86_64/egg/geoserver/catalog.py", line 211, in get_xml
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/geoserver/retry.py", line 9, in decorator
    result = func(_args, *_kwargs)
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/httplib2-0.9-py2.7.egg/httplib2/**init**.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/geoserver/retry.py", line 9, in decorator
    result = func(_args, *_kwargs)
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/httplib2-0.9-py2.7.egg/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/geoserver/retry.py", line 9, in decorator
    result = func(_args, *_kwargs)
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/ext-libs/httplib2-0.9-py2.7.egg/httplib2/__init__.py", line 1291, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt

I suppose that the node browsing is activated but it shouldn't... need a better filtering on drop event and model sync event (if there is a model)

**Comment by volaya** [comment]
the dropping works on any item, just using the parent or default workspace.

Actually, that is what it is doing in your case, but it seems that Geoserver wasnt replying...and that was causing the freezing. Any error message in GeoServer?

**Comment by gioman** [comment]
@luipir cannot replicate this with the latest revision code and boundless suite.

**Comment by luipir** [comment]
np
