### ISSUE TITLE
Error uploading postgis layer

### ISSUE THREAD

**Issue by luipir** [boundlessgeo/qgis-geoserver-plugin#21]
I used elevetion from quickstart project. I saved them in postgis and added to current project with db manager => it is a generic vector point layer with postgresql dataSource 

uploading it to geoserver generate this error:

Tried to make a GET request to http://10.100.100.238:8080/geoserver/rest/workspaces/grancanary/datastores/boundless_quickstart_public/featuretypes/elevation.xml but got a 404 status code: No such feature type: grancanary,boundless_quickstart_public,elevation 
Traceback (most recent call last):
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/gui/explorer.py", line 98, in run
    command(*params)
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/qgis/catalog.py", line 457, in publishLayer
    self.upload(layer, workspace, overwrite, title)
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/qgis/catalog.py", line 323, in upload
    self._publishPostgisLayer(layer, workspace, overwrite, name)
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/qgis/catalog.py", line 248, in _publishPostgisLayer
    layer.crs().authid())
  File "/home/ginetto/.qgis2/python/plugins/webappbuilder/ext-libs/gsconfig-1.0.0-py2.7.egg/geoserver/catalog.py", line 664, in publish_featuretype
    feature_type.fetch()
  File "/home/ginetto/.qgis2/python/plugins/webappbuilder/ext-libs/gsconfig-1.0.0-py2.7.egg/geoserver/support.py", line 174, in fetch
    self.dom = self.catalog.get_xml(self.href)
  File "/home/ginetto/.qgis2/python/plugins/webappbuilder/ext-libs/gsconfig-1.0.0-py2.7.egg/geoserver/catalog.py", line 216, in get_xml
    raise FailedRequestError("Tried to make a GET request to %s but got a %d status code: \n%s" % (rest_url, response.status, content))
FailedRequestError: Tried to make a GET request to http://10.100.100.238:8080/geoserver/rest/workspaces/grancanary/datastores/boundless_quickstart_public/featuretypes/elevation.xml but got a 404 status code: 
No such feature type: grancanary,boundless_quickstart_public,elevation

**Comment by giserd** [comment]
check the geoserver , you will konw the reason why ‘No such feature type’

**Comment by luipir** [comment]
I'll check geoserver log. Thank you @giserd

**Comment by volaya** [comment]
cannot reproduce this. seems like the feature type name is " grancanary,boundless_quickstart_public,elevation" (notice the commas) What is the name of the table (and schema) in postgis? what is the name of the layer in QGIS? There might be an issue with that name, since it is not XML-compliant. The trick is to find where it is creating that name in the code...with those commas

**Comment by luipir** [comment]
struggeling to setup a manageble dev env on osx... I'll check it later

**Comment by gioman** [comment]
@luipir what is the status of this issue?

**Comment by luipir** [comment]
It can be closed @gioman
