### ISSUE TITLE
'module' object has no attribute 'ssl_wrap_socket'

### ISSUE THREAD

**Issue by alpha-beta-soup** [boundlessgeo/qgis-geoserver-plugin#27]
When attempting to install the plugin, I get the following error:

```
Couldn't load plugin 'geoserverexplorer' 

AttributeError: 'module' object has no attribute 'ssl_wrap_socket' 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 269, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 560, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/__init__.py", line 9, in 
    from geoserverexplorer.qgis.catalog import *
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 560, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/qgis/catalog.py", line 17, in 
    import requests
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 560, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/requests-2.0.1-py2.7.egg/requests/__init__.py", line 53, in 
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 560, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/requests-2.0.1-py2.7.egg/requests/packages/urllib3/contrib/pyopenssl.py", line 55, in 
    orig_connectionpool_ssl_wrap_socket = connectionpool.ssl_wrap_socket
AttributeError: 'module' object has no attribute 'ssl_wrap_socket'


Python version: 2.7.9 (default, Apr  2 2015, 15:37:21) [GCC 4.9.2] 
QGIS version: 2.11.0-Master Master, exported 

Python Path:
/usr/share/qgis/python/plugins/processing
/usr/share/qgis/python
/home/richardlaw/.qgis2/python
/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/python_dateutil-2.2-py2.7.egg
/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/six-1.10.0-py2.7.egg
/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/requests-2.0.1-py2.7.egg
/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.0-py2.7.egg
/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/gisdata-0.5.4-py2.7.egg
/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsimporter-1.0.0-py2.7.egg
/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/httplib2-0.9-py2.7.egg
/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.0-py2.7.egg
/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsimporter-1.0.0-py2.7.egg
/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.0-py2.7.egg
/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsimporter-1.0.0-py2.7.egg
/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.0-py2.7.egg
/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsimporter-1.0.0-py2.7.egg
/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.0-py2.7.egg
/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsimporter-1.0.0-py2.7.egg
/home/richardlaw/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/local/lib/python2.7/dist-packages/netCDF4-1.1.9-py2.7-linux-x86_64.egg
/usr/lib/python2.7/dist-packages
/usr/local/lib/python2.7/dist-packages/numpy-1.9.2-py2.7-linux-x86_64.egg
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/home/richardlaw/.local/lib/python2.7/site-packages
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gst-0.10
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/pymodules/python2.7
/usr/lib/python2.7/dist-packages/ubuntu-sso-client
/home/richardlaw/.qgis2//python
.
/usr/share/qgis/python/plugins/fTools/tools
/home/richardlaw/.qgis2/python/plugins/geoserverexplorer/ext-libs
```

Seems to be some issue with requests/PyOpenSSL? Let me know if you need any more details.

**Comment by alpha-beta-soup** [comment]
Seems similar to #14 (issue with requests 2.0.1 on Ubuntu 15.04)

**Comment by luipir** [comment]
seems you have compiled from a not up to date repo... as stated here the problem is solved in request 2.1
https://github.com/kennethreitz/requests/issues/1732

and the installed egg would be 2.5 as stated here:
https://github.com/boundlessgeo/qgis-geoserver-plugin/blob/master/requirements.txt

did you compiled it with paver? did you git pull? did you installed from qgis repo?

**Comment by luipir** [comment]
sorry... I verified that was a packaging mistake uploading a version with updated code but not updated dependecies.
The version in the repo is distributed with 2.0.1 that is an error.
We'll fix soon!

**Comment by alpha-beta-soup** [comment]
Just tried to install it from within QGIS as I was just curious to try it out. Looks pretty interesting.

**Comment by luipir** [comment]
Hi @alpha-beta-soup 
Just a question. Are you able to prepare the current version of the plugin with repo and test on your platform version?
Is just to check if updating to 2.5 would not create dependency problem with other modules in your installation.

**Comment by alpha-beta-soup** [comment]
Yes, but not for two weeks. I'll do it when I get back from holiday :)

**Comment by luipir** [comment]
btw victor has updated the plugin... plase check if it works correctly on you platform. After your check We (or you) will provide to close the ticket if it is solved

thank you for opening the tiket

**Comment by merkato** [comment]
"cannot import name certs", after 0.1.1 update, Ubuntu 15.10

**Comment by luipir** [comment]
checking

**Comment by luipir** [comment]
hi @merkato 

I cannot confirm the bug in my compiled 2.8 and Master version on Ubuntu 15.10

can you give us more detail of the qgis version are you using? e.g cut&paste all you find in Help->about->about of QGIS.

btw if the problem persist.. .please open a new issue beause this issue refers to another versionin problem and I suppose the problem you are referring is not related.

**Comment by alpha-beta-soup** [comment]
I'm no longer having this issue. (Ubuntu 15.04, QGIS 2.14, using the version installed through the QGIS Plugin Manager, same as before).

**Comment by luipir** [comment]
@alpha-beta-soup that means that this issue can be closed?

**Comment by alpha-beta-soup** [comment]
Yes, I think so.
