### ISSUE TITLE
Error when submitting style change

### ISSUE THREAD

**Issue by peterahlstrom** [boundlessgeo/qgis-geoserver-plugin#35]
Thank you for doing this job to make managing Geoserver easier. Much needed! :smiley: 

This happened today:
Chose a style :arrow_forward:  Edit... :arrow_forward:  changed color :arrow_forward:  pressed OK.

> must be string or buffer, not tuple 
> Traceback (most recent call last):
>   File "C:/Users/petahl2/.qgis2/python/plugins\geoserverexplorer\gui\explorer.py", line 98, in run
>     command(*params)
>   File "build\bdist.win32\egg\geoserver\style.py", line 108, in update_body
>     self.body_href, "PUT", body, headers)
>   File "C:/Users/petahl2/.qgis2/python/plugins\geoserverexplorer\geoserver\retry.py", line 14, in decorator
>     raise e
> TypeError: must be string or buffer, not tuple

**Comment by peterahlstrom** [comment]
QGIS version: 2.10.1-Pisa

**Comment by dvictori** [comment]
I'm seeing the same thing using QGis 2.12.3 when I try to change the layer style using the QGis dialog. But I'm able to change the SLD if I type it in the Edit SLD... dialog window.

```
Traceback (most recent call last):
  File "C:/Users/daniel/.qgis2/python/plugins\geoserverexplorer\gui\explorer.py", line 98, in run
    command(*params)
  File "C:\Users\daniel\.qgis2\python\plugins\geoserverexplorer\ext-libs\gsconfig-1.0.0-py2.7.egg\geoserver\style.py", line 108, in update_body
    self.body_href, "PUT", body, headers)
  File "C:/Users/daniel/.qgis2/python/plugins\geoserverexplorer\geoserver\retry.py", line 14, in decorator
    raise e
TypeError: must be string or buffer, not tuple
```

This plugin is great, by the way!

**Comment by purid** [comment]
Same thing with 2.8.2 Geoserver and 2.14.0-Eseen QGIS

**Comment by icthecat** [comment]
Same problem Here. Qgis 2.14.5 (Essen) + Geoserver 2.9 + Geoserver Explorer 0.1.1. I tried to set a diferent fill color on a simple feature (polygon) data loaded from postgis table and got this result:

must be string or buffer, not tuple 
Traceback (most recent call last):
  File "C:/Users/Icaro/.qgis2/python/plugins\geoserverexplorer\gui\explorer.py", line 98, in run
    command(*params)
  File "C:\Users\Icaro\.qgis2\python\plugins\geoserverexplorer\ext-libs\gsconfig-1.0.0-py2.7.egg\geoserver\style.py", line 108, in update_body
    self.body_href, "PUT", body, headers)
  File "C:/Users/Icaro/.qgis2/python/plugins\geoserverexplorer\geoserver\retry.py", line 14, in decorator
    raise e
TypeError: must be string or buffer, not tuple

**Comment by icthecat** [comment]
This issue solved my problem, i hope that help you guys.

https://github.com/boundlessgeo/qgis-geoserver-plugin/commit/e877ab4df051bf225342571bebcc7ab7f2f3945f

**Comment by gioman** [comment]
cannot confirm with the latest version of the plugin and Boundless Suite. Still true?
