### ISSUE TITLE
Geoserer Explorer Plugin stopped working

### ISSUE THREAD

**Issue by purid** [boundlessgeo/qgis-geoserver-plugin#38]
This morning I changed my default password of geoserver and since then publishing layers or projects from QGIS not working using GeoServer Explorer Plugin. I am getting this error while trying to connect to Geoserver with the plugin:

Traceback (most recent call last):
      File "C:/Users/xyz/.qgis2/python/plugins\geoserverexplorer\gui\explorer.py", line 98, in run
        command(*params)
      File "C:/Users/xyz/.qgis2/python/plugins\geoserverexplorer\gui\gsexploreritems.py", line 534, in populate
        raise e
    FailedRequestError
I have changed the password to default again. Reinstalled Geoserver to overwrite the securities and reinstalled QGIS (by deleting the OSGeo4W64 Directory) and deleted the local .qgis2 folder. I am still getting the above error while connecting  to catalog. I can add WMS from geoserver to my QGIS project but I can not publish the layer or project from QGIS. I can edit layers etc. but can't publish a layer or project from QGIS. 

Versions: QGIS : 2.14.1 Essen GeoServer explorer Plugin: 0.1.1 Geoserver: 2.8.2

**Comment by mespinos** [comment]
Same here. I use QGIS 2.14.3 Essen over MacOs X "El Capitan"

I tryed to re-instll module, but nothing change. I didn't try to re-install QGIS.

Seems that plugin can read some info from geoserver, like workspaces, layers and styles.
For instance, When you try to update some isolated style from QGIS layer, module create the style in geoserver, but these style has no any info, no SLD xml.

Thanks to Boundlessgeo and community for that great plugin.

**Comment by gioman** [comment]
@volaya @luipir I cannot confirm the reported problem using the latest revision code and boundless suite. However changing the password and refreshing the catalogs list in the plugin will cause the following error (that goes away of course after the password is changed in the connection parameters) that I guess would be good to catch to return a more friendly warning.

```
Traceback (most recent call last): File "C:/Users/qgis/.qgis2/python/plugins\geoserverexplorer\gui\gsexploreritems.py", line 547, in populate self._populate() File "C:/Users/qgis/.qgis2/python/plugins\geoserverexplorer\gui\gsexploreritems.py", line 560, in _populate self.workspacesItem.populate() File "C:/Users/qgis/.qgis2/python/plugins\geoserverexplorer\gui\gsexploreritems.py", line 399, in populate workspaces = cat.get_workspaces() File "build/bdist.linux-x86_64/egg/geoserver/catalog.py", line 860, in get_workspaces description = self.get_xml("%s/workspaces.xml" % self.service_url) File "build/bdist.linux-x86_64/egg/geoserver/catalog.py", line 216, in get_xml raise FailedRequestError("Tried to make a GET request to %s but got a %d status code: \n%s" % (rest_url, response.status, content)) FailedRequestError: Tried to make a GET request to http://192.168.1.87:8080/geoserver/rest/workspaces.xml but got a 401 status code: 
HTTP Status 401 - No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken
type Status report
message No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken
description This request requires HTTP authentication.

Apache Tomcat/8.0.35 
Traceback (most recent call last):
  File "C:/Users/qgis/.qgis2/python/plugins\geoserverexplorer\gui\explorer.py", line 101, in run
    command(*params)
  File "C:/Users/qgis/.qgis2/python/plugins\geoserverexplorer\gui\gsexploreritems.py", line 552, in populate
    raise Exception(var)
Exception: Traceback (most recent call last):
  File "C:/Users/qgis/.qgis2/python/plugins\geoserverexplorer\gui\gsexploreritems.py", line 547, in populate
    self._populate()
  File "C:/Users/qgis/.qgis2/python/plugins\geoserverexplorer\gui\gsexploreritems.py", line 560, in _populate
    self.workspacesItem.populate()
  File "C:/Users/qgis/.qgis2/python/plugins\geoserverexplorer\gui\gsexploreritems.py", line 399, in populate
    workspaces = cat.get_workspaces()
  File "build/bdist.linux-x86_64/egg/geoserver/catalog.py", line 860, in get_workspaces
    description = self.get_xml("%s/workspaces.xml" % self.service_url)
  File "build/bdist.linux-x86_64/egg/geoserver/catalog.py", line 216, in get_xml
    raise FailedRequestError("Tried to make a GET request to %s but got a %d status code: \n%s" % (rest_url, response.status, content))
FailedRequestError: Tried to make a GET request to http://192.168.1.87:8080/geoserver/rest/workspaces.xml but got a 401 status code: 

HTTP Status 401 - No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken
type Status report
message No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken
description This request requires HTTP authentication.

Apache Tomcat/8.0.35
```
