### ISSUE TITLE
error when importing vectors with style categories containing special chars

### ISSUE THREAD

**Issue by skyforbird** [boundlessgeo/qgis-geoserver-plugin#44]
I'm in China. My PC is Windows 7 64bit in Chinese.  I found this plugin does not support chinese encode.

1.When i publish a shp layer with layer name and field value in Chinese to GeoServer ,i got error: "UnicodeEncodeError: 'ascii' codec can't encode characters in position 681-684: ordinal not in range(128)"

2.When i add a new style from QGIS also got the same error.

**Comment by gioman** [comment]
This issue is not specific for chinese, I'm hitting the same issue with Portuguese. If a layer (postgis in my case) has a legend with special chars (ã,é, etc.) importing in geoserver fails with a similar error:

```
Traceback (most recent call last):

  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/explorer.py", line 101, in run

    command(*params)

  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/confirm.py", line 18, in publishLayer

    catalog.publishLayer(layer, workspace, True, name)

  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/qgis/catalog.py", line 493, in publishLayer

    sld = self.publishStyle(layer, overwrite, name) if style is None else None

  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/qgis/catalog.py", line 164, in publishStyle

    self.catalog.create_style(name, sld, overwrite)

  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.0-py2.7.egg/geoserver/catalog.py", line 841, in create_style

    headers, response = self.http.request(body_href, "PUT", data, headers)

  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/geoserver/retry.py", line 19, in decorator

    raise e

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 531: ordinal not in range(128)
```

**Comment by gioman** [comment]
error is similar to the one reported here https://github.com/boundlessgeo/qgis-geoserver-plugin/issues/43

**Comment by gioman** [comment]
Still same kind of error when importing a shape that has style categories with special chars. Attached a sample (style with "name" column):

```
Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/explorer.py", line 101, in run
    command(*params)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/confirm.py", line 20, in publishLayer
    catalog.publishLayer(layer, workspace, True, name)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/qgis/catalog.py", line 503, in publishLayer
    sld = self.publishStyle(layer, overwrite, name) if style is None else None
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/qgis/catalog.py", line 172, in publishStyle
    self.catalog.create_style(name, sld, overwrite)
  File "build/bdist.linux-x86_64/egg/geoserver/catalog.py", line 841, in create_style
    headers, response = self.http.request(body_href, "PUT", data, headers)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/geoserver/networkaccessmanager.py", line 170, in request
    self.reply = func(req, body)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 526-533: ordinal not in range(256)

[shape.zip](https://github.com/boundlessgeo/qgis-geoserver-plugin/files/866299/shape.zip)

```

**Comment by gioman** [comment]
see also https://github.com/boundlessgeo/qgis-geoserver-plugin/issues/61

**Comment by gioman** [comment]
Testing the latest revision code against GS 2.11, importing a vector with a categorized symbology with classes with special chars still fails:

```
Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/explorer.py", line 101, in run
    command(*params)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/confirm.py", line 20, in publishLayer
    catalog.publishLayer(layer, workspace, True, name)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/qgis/catalog.py", line 503, in publishLayer
    sld = self.publishStyle(layer, overwrite, name) if style is None else None
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/qgis/catalog.py", line 172, in publishStyle
    self.catalog.create_style(name, sld, overwrite)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.6-py2.7.egg/geoserver/catalog.py", line 840, in create_style
    headers, response = self.http.request(body_href, "PUT", data, headers)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/geoserver/retry.py", line 18, in decorator
    raise e
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc7' in position 2390: ordinal not in range(128)
```

**Comment by jacobwod** [comment]
This can't be too uncommon, given that both QGIS and GeoServer are quite popular globally. 

Are there any known work-arounds that would still give correct (non-ascii) characters in the legend shown to the user?

![2017-11-22 13_58_53-qgis 2 18 13 - test to postgis](https://user-images.githubusercontent.com/110222/33128622-597215a6-cf8d-11e7-9b8e-4624b0023679.png)

**Comment by jacobwod** [comment]
The issue still remains, but I'll give an answer to my own question regarding work-around.

The solution is to export style as SLD file in QGIS (in layer properties, tab Styles, there's a button in the buttom left corner named "Style...", from where you can export to SLD). When you have the SLD file, open it and copy it's contents to the clipboard. Then switch to GeoServer, Styles->Add a new style, and paste the copied SLD text into Style editor. Make sure to pick SLD as Format as well. Apply and you're done.

Not a solution though and the issue remains.
