### ISSUE TITLE
Error while exporting style to Geoserver

### ISSUE THREAD

**Issue by Jerry-kiwi** [boundlessgeo/qgis-geoserver-plugin#61]
Traceback (most recent call last):
  File "/home/www_adm/.qgis2/python/plugins/geoserverexplorer/gui/explorer.py", line 101, in run
    command(*params)
  File "/home/www_adm/.qgis2/python/plugins/geoserverexplorer/qgis/catalog.py", line 500, in publishLayer
    sld = self.publishStyle(layer, overwrite, name) if style is None else None
  File "/home/www_adm/.qgis2/python/plugins/geoserverexplorer/qgis/catalog.py", line 171, in publishStyle
    self.catalog.create_style(name, sld, overwrite)
  File "/home/www_adm/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.6-py2.7.egg/geoserver/catalog.py", line 840, in create_style
    headers, response = self.http.request(body_href, "PUT", data, headers)
  File "/home/www_adm/.qgis2/python/plugins/geoserverexplorer/geoserver/retry.py", line 19, in decorator
    raise e
UnicodeEncodeError: 'ascii' codec can't encode characters in position 640-652: ordinal not in range(128)

QGIS 2.18
Ubuntu 16.04
Geoserver 2.10.1
Shape file from OSM withh russian symbols (download from gis-lab)

**Comment by Jerry-kiwi** [comment]
Geoserver plugin 0.5

**Comment by gioman** [comment]
> Geoserver plugin 0.5

could you give a try to master?

https://github.com/boundlessgeo/qgis-geoserver-plugin/archive/master.zip

thanks!

**Comment by Jerry-kiwi** [comment]
Thanks for help
What is the correct way to install it over current module? In order to keep experiment clear^)?

**Comment by Jerry-kiwi** [comment]
WARNING AFTER START:
2017-02-12T15:14:44	1	warning:/home/www_adm/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.6-py2.7.egg/geoserver/layer.py:132: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
			
			traceback:  File "/home/www_adm/.qgis2/python/plugins/geoserverexplorer/gui/explorertree.py", line 103, in treeItemDoubleClicked
			    action.trigger()
			  File "/home/www_adm/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 624, in <lambda>
			    editAction.triggered.connect(lambda: self.editCatalog(explorer))
			  File "/home/www_adm/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 656, in editCatalog
			    self.refreshContent(explorer)
			  File "/home/www_adm/.qgis2/python/plugins/geoserverexplorer/gui/exploreritems.py", line 29, in refreshContent
			    explorer.run(self.populate, None, [])
			  File "/home/www_adm/.qgis2/python/plugins/geoserverexplorer/gui/explorer.py", line 101, in run
			    command(*params)
			  File "/home/www_adm/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 547, in populate
			    self._populate()
			  File "/home/www_adm/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 564, in _populate
			    self.layersItem.populate()
			  File "/home/www_adm/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 345, in populate
			    layerItem.populate()
			  File "/home/www_adm/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 712, in populate
			    for style in layer.styles:
			  File "build/bdist.linux-x86_64/egg/geoserver/layer.py", line 148, in _get_alternate_styles
			    return filter(None, [ self._resolve_style(s) for s in styles_list ])
			  File "build/bdist.linux-x86_64/egg/geoserver/layer.py", line 132, in _resolve_style
			    atom_link = [ n for n in element.getchildren() if 'href' in n.attrib ]


ERROT AFTER ADDING LAYER TO GEOSERVER

![2017-02-12 15-18-30 192 168 1 38](https://cloud.githubusercontent.com/assets/8778463/22862001/f54df958-f136-11e6-9403-b0c5c04c358a.png)

**Comment by gioman** [comment]
likely duplicated of https://github.com/boundlessgeo/qgis-geoserver-plugin/issues/44
