### ISSUE TITLE
Unescaped url when store name contain space

### ISSUE THREAD

**Issue by tkumpumaki** [boundlessgeo/qgis-geoserver-plugin#63]
If you have store name with a space character like "store name" in Geoserver and try to fetch layers with the geoserver explorer on QGIS, plugin fails to proceed to fetch available layers.

**Comment by gioman** [comment]
Confirmed here using the latest revision code against Suite 4.9

**Comment by gioman** [comment]
If the store with spaces is a WMS cascading one, then it will cause this error (does not happen if the store name has no spaces):

`Could not connect to catalog: Traceback (most recent call last): File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 313, in addGeoServerCatalog geoserverItem.populate() File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 552, in populate raise Exception(var) Exception: Traceback (most recent call last): File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 547, in populate self._populate() File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 560, in _populate self.workspacesItem.populate() File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 402, in populate workspaceItem.populate() File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 1248, in populate storeItem.populate() File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 1313, in populate resources = self.element.get_resources() File "build/bdist.linux-x86_64/egg/geoserver/store.py", line 207, in get_resources xml = self.catalog.get_xml(res_url) File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/geoserver/auth.py", line 71, in get_xml response, content = self.http.request(rest_url) File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/geoserver/networkaccessmanager.py", line 219, in request raise self.exception_class(self.http_call_result.reason) FailedRequestError: Network error #203: Error downloading http://suite.boundless.test:8080/geoserver/rest/workspaces/opengeo/wmsstores/o%20meu%20store2/wmslayers.xml - server replied: Not Found `

**Comment by gioman** [comment]
The same issue does also show when special chars are in the workspace or layers names.

**Comment by volaya** [comment]
I cannot reproduce it in the case of blank spaces, using a standard geoserver.

Could you add here the stack trace that you get, to see where the error might be?

In the case of non-ascii chars, the issues is in the gsconfig library, in here:

https://github.com/boundlessgeo/gsconfig/blob/master/src/geoserver/catalog.py#L201

I will try to fix it there. If not, will add something in the GeoServer plugin to more gracefully handle this kind of errors.

**Comment by tkumpumaki** [comment]
Some student has made a layer with space again... It gives following stack trace on QGIS. As you see it tries to fetch from url with space character unescaped. I don't know if the urls should come from geoserver as valid url:s or is the problem on Geoserver explorer side. Anyway if the problem is on geoserver side, the error handling could be improved on plugin side to not be a showstopper for all layers in case of one bad layer name.

Versions:
Geoserver explorer:  0.5 
QGIS: 2.18.4
Geoserver: 2.11-SNAPSHOT

Tried to make a GET request to http://x.x.x.x:8080/geoserver/rest/workspaces/kglad/wmsstores/Helsinki wms/wmslayers.xml but got a 400 status code: 
Traceback (most recent call last):
  File "C:/ xxx/.qgis2/python/plugins\geoserverexplorer\gui\explorer.py", line 101, in run
    command(*params)
  File "C:/ xxx/.qgis2/python/plugins\geoserverexplorer\gui\gsexploreritems.py", line 551, in populate
    raise e
FailedRequestError: Tried to make a GET request to http://x.x.x.x:8080/geoserver/rest/workspaces/kglad/wmsstores/Helsinki wms/wmslayers.xml but got a 400 status code:

**Comment by gioman** [comment]
@volaya tested with plugin master from dev repo and geoserver 2.11.

I also cannot confirm anymore the issue with space in stores names unless the store is a WMS cascading one, in this case an error is returned:


```
Traceback (most recent call last): File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 547, in populate self._populate() File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 560, in _populate self.workspacesItem.populate() File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 402, in populate workspaceItem.populate() File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 1248, in populate storeItem.populate() File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 1313, in populate resources = self.element.get_resources() File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.6-py2.7.egg/geoserver/store.py", line 207, in get_resources xml = self.catalog.get_xml(res_url) File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.6-py2.7.egg/geoserver/catalog.py", line 216, in get_xml raise FailedRequestError("Tried to make a GET request to %s but got a %d status code: \n%s" % (rest_url, response.status, content)) FailedRequestError: Tried to make a GET request to http://x.x.x.x/geoserver/rest/workspaces/cite/wmsstores/azz azz/wmslayers.xml but got a 400 status code: 
Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/explorer.py", line 101, in run
    command(*params)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 552, in populate
    raise Exception(var)
Exception: Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 547, in populate
    self._populate()
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 560, in _populate
    self.workspacesItem.populate()
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 402, in populate
    workspaceItem.populate()
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 1248, in populate
    storeItem.populate()
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 1313, in populate
    resources = self.element.get_resources()
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.6-py2.7.egg/geoserver/store.py", line 207, in get_resources
    xml = self.catalog.get_xml(res_url)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.6-py2.7.egg/geoserver/catalog.py", line 216, in get_xml
    raise FailedRequestError("Tried to make a GET request to %s but got a %d status code: \n%s" % (rest_url, response.status, content))
FailedRequestError: Tried to make a GET request to http://x.x.x.x/geoserver/rest/workspaces/cite/wmsstores/azz azz/wmslayers.xml but got a 400 status code: 
```

and other error is returned even if this type of stores has no spaces in their names:


```
Tried to make a GET request to http://x.x.x.x/geoserver/rest/workspaces/cite/wmsstores/azz_azz/wmslayers/Bacias_hidrográficas.xml but got a 404 status code: No such cascaded wms layer: cite,azz_azz,Bacias_hidrogr%C3%A1ficas 
Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/explorer.py", line 101, in run
    command(*params)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 344, in populate
    layerItem = GsLayerItem(layer)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 705, in __init__
    GsTreeItem.__init__(self, layer, icon, layer.resource.title)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.6-py2.7.egg/geoserver/support.py", line 67, in getter
    self.fetch()
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.6-py2.7.egg/geoserver/support.py", line 176, in fetch
    self.dom = self.catalog.get_xml(self.href)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.6-py2.7.egg/geoserver/catalog.py", line 216, in get_xml
    raise FailedRequestError("Tried to make a GET request to %s but got a %d status code: \n%s" % (rest_url, response.status, content))
FailedRequestError: Tried to make a GET request to http://x.x.x.x./geoserver/rest/workspaces/cite/wmsstores/azz_azz/wmslayers/Bacias_hidrogr\xe1ficas.xml but got a 404 status code: 
No such cascaded wms layer: cite,azz_azz,Bacias_hidrogr%C3%A1ficas
```


let me know when there is a fix/warning for special chars.

**Comment by gioman** [comment]
Filed a different ticker for WMS cascading stores: https://github.com/boundlessgeo/qgis-geoserver-plugin/issues/69
