### ISSUE TITLE
Catalog definition

### ISSUE THREAD

**Issue by sunshine0576** [boundlessgeo/qgis-geoserver-plugin#64]
Traceback (most recent call last):
  File "C:/Users/PC8651/.qgis2/python/plugins\geoserverexplorer\gui\explorer.py", line 101, in run
    command(*params)
  File "C:/Users/PC8651/.qgis2/python/plugins\geoserverexplorer\gui\gsexploreritems.py", line 551, in populate
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcb in position 41: ordinal not in range(128)

**Comment by gioman** [comment]
@sunshine0576  Hi, could you detail a little bit more?

**Comment by gioman** [comment]
Without any detail is hard to confirm/troubleshoot.
