### ISSUE TITLE
python error if workspace name contauns special chars

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geoserver-plugin#70]
tested against GS 2.11 with plugin master revision code

Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/explorer.py", line 101, in run
    command(*params)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 559, in populate
    raise Exception(var)
Exception: Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 554, in populate
    self._populate()
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 567, in _populate
    self.workspacesItem.populate()
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 409, in populate
    workspaceItem.populate()
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 1254, in populate
    stores = self.element.catalog.get_stores(self.element)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.6-py2.7.egg/geoserver/catalog.py", line 297, in get_stores
    ds_list = self.get_xml(workspace.datastore_url)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/geoserver/basecatalog.py", line 143, in get_xml
    raise FailedRequestError("Tried to make a GET request to %s but got a %d status code: \n%s" % (rest_url, response.status, content))
FailedRequestError: Tried to make a GET request to http://193.136.217.226/geoserver/rest/workspaces/ftt/datastores.xml but got a 404 status code: 
No such workspace: ftt

**Comment by gioman** [comment]
error when store has a special char in its name

`Traceback (most recent call last): File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 554, in populate self._populate() File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 567, in _populate self.workspacesItem.populate() File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 409, in populate workspaceItem.populate() File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 1259, in populate storeItem.populate() File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 1332, in populate resources = self.element.get_resources() File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/ext-libs/gsconfig-1.0.6-py2.7.egg/geoserver/store.py", line 68, in get_resources xml = self.catalog.get_xml(res_url) File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/geoserver/basecatalog.py", line 143, in get_xml raise FailedRequestError("Tried to make a GET request to %s but got a %d status code: \n%s" % (rest_url, response.status, content)) FailedRequestError: Tried to make a GET request to http://193.136.217.226/geoserver/rest/workspaces/ftto/datastores/ubc_t1/featuretypes.xml but got a 404 status code: No such datastore: ftto,ubc_t1 `
