### ISSUE TITLE
Problem with _populate

### ISSUE THREAD

**Issue by DanielAccorsi** [boundlessgeo/qgis-geoserver-plugin#74]
After create catalog, when trying to refresh, shows this error:

> Traceback (most recent call last):
>   File "/home/daniel/.qgis2/python/plugins/geoserverexplorer/gui/explorer.py", line 98, in run
>     command(*params)
>   File "/home/daniel/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 534, in populate
>     raise e
> error: [Errno 9] Bad file descriptor

Thanks!

**Comment by gioman** [comment]
@DanielAccorsi Hi, can you give us more details? Geoserver version, plugin version, platform where QGIS runs, QGIS version, etc. Thanks!

**Comment by gioman** [comment]
@DanielAccorsi any feedback?

**Comment by volaya** [comment]
That error is usually caused by some print statement (probably used for debugging and left there unintentionally) that cannot print because the console is not open. Could you open the Python console and retry?

I see no print line in the line that is reported by the stack trace, but he might be using an older version
