### ISSUE TITLE
failing tests against Suite 4.9 (not PKI)

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geoserver-plugin#75]
Running tester plugin tests with plugin master version against Suite 4.9 there are failing tests in both the automated ones and the manual ones. Attached the reports.

[28411f60-ef54-4331-a20b-9f0fd0c53d43.zip](https://github.com/boundlessgeo/qgis-geoserver-plugin/files/1061180/28411f60-ef54-4331-a20b-9f0fd0c53d43.zip)

**Comment by gioman** [comment]
important note: using QGIS 2.18.9 "head"

**Comment by gioman** [comment]
@volaya this is about non PKI tests

**Comment by luipir** [comment]
I just run NO PKI automated tests against https://github.com/boundlessgeo/docker/tree/master/compose-desktop-testing 

and succes all but the last one!

**Comment by elpaso** [comment]
Working on that.

**Comment by elpaso** [comment]
Maybe fixed in https://github.com/boundlessgeo/qgis-geoserver-plugin/commit/0f03e45e873d14e53db8f09f8274ead28a8e78a9

**Comment by gioman** [comment]
@elpaso @volaya  @luipir at a first look I would say yes. 

@volaya please notice that with this patch there are still 2 tests in Tester plugin that are failing. 1 in manual tests the other in the automatic ones. Note that in the tests you make use of a .qgs project that has an hardcoded full path to a datasource, that maybe the source of the problem for both fails:

![screenshot_20170615_180713](https://user-images.githubusercontent.com/1951107/27193514-fb97abd0-51f6-11e7-9d50-b8b3faf84872.png)

The errors:

```
Test name: GeoServer-geoserverexplorer.test.symbologytests.SymbologyTests.testVectorFontStylingUpload

Test result:Test failed at step 'Run unit test' with message:

(<type 'exceptions.AssertionError'>, AssertionError(u'SLD compare failes: <?xmlversion="1.0"encoding="UTF-8"?><StyledLayerDescriptorxmlns="http://www.opengis.net/sld"xmlns:ogc="http://www.opengis.net/ogc"xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"version="1.0.0"xmlns:xlink="http://www.w3.org/1999/xlink"xsi:schemaLocation="http://www.opengis.net/sldhttp://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd"xmlns:sld="http://www.opengis.net/sld"><NamedLayer><sld:Name>qgis_plugin_test_pt1</sld:Name><UserStyle><sld:Name>qgis_plugin_test_pt1</sld:Name><sld:FeatureTypeStyle><sld:Rule><sld:Name>Singlesymbol</sld:Name><sld:PointSymbolizer><sld:Graphic>\t<sld:Mark>\t\t<WellKnownName>ttf://DejaVuSans#0x46</WellKnownName>\t\t<sld:Fill>\t\t\t<CssParametername="fill">#570cd7</CssParameter>\t\t</sld:Fill>\t</sld:Mark>\t<sld:Size>7.000000</sld:Size></sld:Graphic></sld:PointSymbolizer></sld:Rule></sld:FeatureTypeStyle></UserStyle></NamedLayer></StyledLayerDescriptor> <?xmlversion="1.0"encoding="UTF-8"?><StyledLayerDescriptorxmlns="http://www.opengis.net/sld"xmlns:ogc="http://www.opengis.net/ogc"xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"version="1.0.0"xmlns:xlink="http://www.w3.org/1999/xlink"xsi:schemaLocation="http://www.opengis.net/sldhttp://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd"xmlns:sld="http://www.opengis.net/sld"><NamedLayer><sld:Name>qgis_plugin_test_pt1</sld:Name><UserStyle><sld:Name>qgis_plugin_test_pt1</sld:Name><sld:FeatureTypeStyle><sld:Rule><sld:Name>Singlesymbol</sld:Name><sld:PointSymbolizer><sld:Graphic><sld:Mark><WellKnownName>ttf://DejaVuSans#0x46</WellKnownName><sld:Fill><CssParametername="fill">#570cd7</CssParameter></sld:Fill></sld:Mark><sld:Size>7</sld:Size></sld:Graphic></sld:PointSymbolizer></sld:Rule></sld:FeatureTypeStyle></UserStyle></NamedLayer></StyledLayerDescriptor>',), <traceback object at 0x7f63cc2e4dd0>)

File "/usr/lib/python2.7/unittest/case.py", line 329, in run

testMethod()

File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/test/symbologytests.py", line 63, in testVectorFontStylingUpload

self.compareSld(sldref, sld)

File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/test/symbologytests.py", line 51, in compareSld

self.assertEqual(a, b, "SLD compare failes: %s %s" % (a, b))

File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual

assertion_func(first, second, msg=msg)

File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual

raise self.failureException(msg)


Traceback (most recent call last):

File "/home/giovanni/.qgis2/python/plugins/qgistester/testerwidget.py", line 119, in runNextStep

execute(step.function)

File "/home/giovanni/.qgis2/python/plugins/qgistester/utils.py", line 70, in execute

return func()

File "/home/giovanni/.qgis2/python/plugins/qgistester/test.py", line 66, in _runTest

raise Exception(desc)

Exception: (<type 'exceptions.AssertionError'>, AssertionError(u'SLD compare failes: <?xmlversion="1.0"encoding="UTF-8"?><StyledLayerDescriptorxmlns="http://www.opengis.net/sld"xmlns:ogc="http://www.opengis.net/ogc"xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"version="1.0.0"xmlns:xlink="http://www.w3.org/1999/xlink"xsi:schemaLocation="http://www.opengis.net/sldhttp://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd"xmlns:sld="http://www.opengis.net/sld"><NamedLayer><sld:Name>qgis_plugin_test_pt1</sld:Name><UserStyle><sld:Name>qgis_plugin_test_pt1</sld:Name><sld:FeatureTypeStyle><sld:Rule><sld:Name>Singlesymbol</sld:Name><sld:PointSymbolizer><sld:Graphic>\t<sld:Mark>\t\t<WellKnownName>ttf://DejaVuSans#0x46</WellKnownName>\t\t<sld:Fill>\t\t\t<CssParametername="fill">#570cd7</CssParameter>\t\t</sld:Fill>\t</sld:Mark>\t<sld:Size>7.000000</sld:Size></sld:Graphic></sld:PointSymbolizer></sld:Rule></sld:FeatureTypeStyle></UserStyle></NamedLayer></StyledLayerDescriptor> <?xmlversion="1.0"encoding="UTF-8"?><StyledLayerDescriptorxmlns="http://www.opengis.net/sld"xmlns:ogc="http://www.opengis.net/ogc"xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"version="1.0.0"xmlns:xlink="http://www.w3.org/1999/xlink"xsi:schemaLocation="http://www.opengis.net/sldhttp://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd"xmlns:sld="http://www.opengis.net/sld"><NamedLayer><sld:Name>qgis_plugin_test_pt1</sld:Name><UserStyle><sld:Name>qgis_plugin_test_pt1</sld:Name><sld:FeatureTypeStyle><sld:Rule><sld:Name>Singlesymbol</sld:Name><sld:PointSymbolizer><sld:Graphic><sld:Mark><WellKnownName>ttf://DejaVuSans#0x46</WellKnownName><sld:Fill><CssParametername="fill">#570cd7</CssParameter></sld:Fill></sld:Mark><sld:Size>7</sld:Size></sld:Graphic></sld:PointSymbolizer></sld:Rule></sld:FeatureTypeStyle></UserStyle></NamedLayer></StyledLayerDescriptor>',), <traceback object at 0x7f63cc2e4dd0>)

File "/usr/lib/python2.7/unittest/case.py", line 329, in run

testMethod()

File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/test/symbologytests.py", line 63, in testVectorFontStylingUpload

self.compareSld(sldref, sld)

File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/test/symbologytests.py", line 51, in compareSld

self.assertEqual(a, b, "SLD compare failes: %s %s" % (a, b))

File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual

assertion_func(first, second, msg=msg)

File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual

raise self.failureException(msg)
```








```
Test name: GeoServer-Verify rendering of uploaded style

Test result:Test failed at step 'Preparing data' with message:


Traceback (most recent call last):

File "/home/giovanni/.qgis2/python/plugins/qgistester/testerwidget.py", line 142, in runNextStep

execute(step.function)

File "/home/giovanni/.qgis2/python/plugins/qgistester/utils.py", line 70, in execute

return func()

File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/test/utils.py", line 403, in openAndUpload

assert wmsLayer.isValid()

AssertionError
```

**Comment by volaya** [comment]
@gioman I can confirm the failure. Will work on fixing them

However, the error you report with the project is weird. The project has a relative path (I just checked and it is defined in the qgs file as "<datasource>./qgis_plugin_test_pt1.shp</datasource>"), and qgis is resolving it to that windows path (although it seems you are in linux there). Maybe some issue with running VMs?

It's similar to the issue you were having with certain test projects for WAB, and that @luipir and I could not replicate...

**Comment by volaya** [comment]
my fault...i was looking in the wrong project. You are right in that there is a hardcoded path.

The other issue, in the manual tests, I have been able to fix it. Will push changes once i have both running and i check that other tests do not break

**Comment by volaya** [comment]
tests are already fixed, can this be closed?

**Comment by gioman** [comment]
> tests are already fixed, can this be closed?

yes I guess so.
