### ISSUE TITLE
python error when clicking on "edit" (in the plugin icon bar) after having already established a connection

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geoserver-plugin#80]
"Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 633, in 
    editAction.triggered.connect(lambda: self.editCatalog(explorer))
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 639, in editCatalog
    dlg = DefineCatalogDialog(explorer.catalogs(), explorer, self.catalog, self.name)
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/dialogs/catalogdialog.py", line 21, in __init__
    self.initGui()
  File "/home/giovanni/.qgis2/python/plugins/geoserverexplorer/gui/dialogs/catalogdialog.py", line 36, in initGui
    settings = QSettings()
NameError: global name 'QSettings' is not defined"

seen on Windows and Linux

**Comment by gioman** [comment]
plugin: master
qgis: 2.18.9
Suite: 4.9 and 4.10
