### ISSUE TITLE
several automated tests (tester plugin) fails against Suite 4.10

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geoserver-plugin#84]
They all pass against Suite 4.9, but against 4.10 a number of them fails against Suite 4.10. The error seems always the same

```
Test name: GeoServer-geoserverexplorer.test.deletetests.DeleteTests.testDeleteGWCLayer
Test result:Test failed at step 'Run unit test' with message:
(<type 'exceptions.AssertionError'>, AssertionError("Tried to create workspace but got 500: :Namespace with URI 'http://test.com' already exists.",), <traceback object at 0x0000000023D2B988>)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\unittest\suite.py", line 146, in _handleClassSetUp
    setUpClass()
  File "C:/Users/boundless/.qgis2/python/plugins\geoserverexplorer\test\deletetests.py", line 22, in setUpClass
    super(DeleteTests, cls).setUpClass()
  File "C:/Users/boundless/.qgis2/python/plugins\geoserverexplorer\test\integrationtest.py", line 32, in setUpClass
    utils.populateCatalog(cls.cat)
  File "C:/Users/boundless/.qgis2/python/plugins\geoserverexplorer\test\utils.py", line 147, in populateCatalog
    cat.create_workspace(WORKSPACE, "http://test.com")
  File "C:\Users\boundless\.qgis2\python\plugins\geoserverexplorer\ext-libs\gsconfig-1.0.6-py2.7.egg\geoserver\catalog.py", line 855, in create_workspace
    assert 200 <= headers.status < 300, "Tried to create workspace but got " + str(headers.status) + ": " + response

Traceback (most recent call last):
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\testerwidget.py", line 119, in runNextStep
    execute(step.function)
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\utils.py", line 70, in execute
    return func()
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\test.py", line 66, in _runTest
    raise Exception(desc)
Exception: (<type 'exceptions.AssertionError'>, AssertionError("Tried to create workspace but got 500: :Namespace with URI 'http://test.com' already exists.",), <traceback object at 0x0000000023D2B988>)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\unittest\suite.py", line 146, in _handleClassSetUp
    setUpClass()
  File "C:/Users/boundless/.qgis2/python/plugins\geoserverexplorer\test\deletetests.py", line 22, in setUpClass
    super(DeleteTests, cls).setUpClass()
  File "C:/Users/boundless/.qgis2/python/plugins\geoserverexplorer\test\integrationtest.py", line 32, in setUpClass
    utils.populateCatalog(cls.cat)
  File "C:/Users/boundless/.qgis2/python/plugins\geoserverexplorer\test\utils.py", line 147, in populateCatalog
    cat.create_workspace(WORKSPACE, "http://test.com")
  File "C:\Users\boundless\.qgis2\python\plugins\geoserverexplorer\ext-libs\gsconfig-1.0.6-py2.7.egg\geoserver\catalog.py", line 855, in create_workspace
    assert 200 <= headers.status < 300, "Tried to create workspace but got " + str(headers.status) + ": " + response
```

**Comment by gioman** [comment]
closing ad invalid.
