### ISSUE TITLE
TypeError: argument of type 'Workspace' is not iterable

### ISSUE THREAD

**Issue by jgrocha** [boundlessgeo/qgis-geoserver-plugin#87]
Hi,

I'm not able to run the tests (on master) with success. I'm also not able to get the plugin running. I'm trying to find out the problem.
Meanwhile, if someone else finds the problem, please share.

Error during tests (running `rundockertests.sh`):
```text
ERROR: setUpClass (geoserverexplorer.test.dragdroptests.DragDropTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.qgis2/python/plugins/geoserverexplorer/test/integrationtest.py", line 33, in setUpClass
    utils.populateCatalog(cls.cat)
  File "/root/.qgis2/python/plugins/geoserverexplorer/test/utils.py", line 148, in populateCatalog
    cleanCatalog(cat)
  File "/root/.qgis2/python/plugins/geoserverexplorer/test/utils.py", line 135, in cleanCatalog
    for store in cat.get_stores(ws):
  File "build/bdist.linux-x86_64/egg/geoserver/catalog.py", line 310, in get_stores
    if store.name in names:
TypeError: argument of type 'Workspace' is not iterable
```

Error running installed version (after `paver install`):
```text
Traceback (most recent call last):
  File "/home/jgr/.qgis2/python/plugins/geoserverexplorer/gui/explorer.py", line 102, in run
    command(*params)
  File "/home/jgr/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 559, in populate
    raise Exception(var)
Exception: Traceback (most recent call last):
  File "/home/jgr/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 554, in populate
    self._populate()
  File "/home/jgr/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 567, in _populate
    self.workspacesItem.populate()
  File "/home/jgr/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 410, in populate
    workspaceItem.populate()
  File "/home/jgr/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 1266, in populate
    stores = self.element.catalog.get_stores(self.element)
  File "/home/jgr/.qgis2/python/plugins/geoserverexplorer/extlibs/gsconfig-1.0.8-py2.7.egg/geoserver/catalog.py", line 310, in get_stores
    if store.name in names:
TypeError: argument of type 'Workspace' is not iterable
```

**Comment by jgrocha** [comment]
Might be related with this PR https://github.com/boundlessgeo/gsconfig/pull/173/commits/90277823595d2e2b82cb0d9c37690a6a3eb50802

**Comment by jgrocha** [comment]
Apparently, the error is on `geoserverexplorer/gui/gsexploreritems.py`:
```python
    def populate(self):
        stores = self.element.catalog.get_stores(self.element)
```

Removing the argument, it works:
```python
    def populate(self):
        stores = self.element.catalog.get_stores()
```

The signature (in `geoserverexplorer/ext-src/gsconfig/src/geoserver/catalog.py`) is:
```python
    def get_stores(self, names=None, workspace=None):
```

**Comment by jgrocha** [comment]
As a work around  I've used `cat.delete(ws, recurse=True)` instead of iterating over all stores in workspace, in `geoserverexplorer/test/utils.py`

**Comment by jgrocha** [comment]
I can not run the plugin with:
```python
    def populate(self):
        stores = self.element.catalog.get_stores(self.element)
```
on `geoserverexplorer/gui/gsexploreritems.py`

I'll submit a PR to change this call to:
```python
    def populate(self):
        stores = self.element.catalog.get_stores()
```

**Comment by SrNetoChan** [comment]
@jgrocha can you test the current master branchn to see if it still happens? It has been ported to work in QGIS 3.X
