### ISSUE TITLE
Not working with QGIS  v3.0

### ISSUE THREAD

**Issue by JohnHenrySpike** [boundlessgeo/qgis-geoserver-plugin#89]
Do you plan to update the plug-in for QGIS version 3.0?

**Comment by landryb** [comment]
It seems there's a `qgis3` branch in the repo with recent commits, cf https://github.com/boundlessgeo/qgis-geoserver-plugin/tree/qgis3 .. so there is hope :)

**Comment by landryb** [comment]
Fwiw, i've installed it locally using the `paver setup` & `paver install` steps from this `qgis3` branch, and the plugin loads fine in my qgis 3.2.2 (just added the python3 version of httplib2 as a dependency) and it connects fine to a remote 2.12.1 geoserver. Kudos @volaya :)

**Comment by volaya** [comment]
Thanks!

The plugin is still rather untested (I adapted some of the tester plugin tests, but not all are passing)

I did quite a bit of manual testing, and it seems to be working fine, but due to the complexity of the plugin, still some stuff might not work as before. Once we test it correctly and it works fine, the qgis3 branch will be merged into master and a new version will be released

Let us know if you find issues.

Regards

**Comment by landryb** [comment]
I've been able to browse a simple 2.12.1 sandbox install with very few layers/workspaces, but when i try to modify a setting/layer attribute/style i only get HTTP 400 code from geoserver, apparently because the PUT calls have a `Content-Length` header set to 0. But i'm not sure this is the plugin's fault, it might be the proxyies in between.. although i'm able to PUT ftl templates via jericks/geoserver-shell so the API itself seems to be working.

On my production instance running 2.8.1 loading the info from the REST api (at the first connect) goes into an infinite loop, ie it queries info all workspaces/layers/datastores/featuretype over and over again (i see the queries in the server log), never stopping.

I dunno if it's a consequence of the qgis3 porting, will have to compare against a older version on qgis2, but iirc we saw the same thing (endless loop when collecting server info) when testing with a colleague of mine on qgis2, so it might be distinct bugs.

**Comment by landryb** [comment]
in the catalog tree, select a a layer, click 'modify' next to the layer title, enter new value, validate, returns `Geoserver: Failed to save to Geoserver catalog: 400, `, full message is:
```
2018-09-12T15:27:35     CRITICAL    Failed to save to Geoserver catalog: 400, :Traceback (most recent call last):
              File "/home/landry/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/gui/explorer.py", line 105, in run
              command(*params)
              File "/home/landry/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/extlibs/geoserver/catalog.py", line 260, in save
              raise FailedRequestError('Failed to save to Geoserver catalog: {}, {}'.format(resp.status_code, resp.text))
             geoserver.catalog.FailedRequestError: Failed to save to Geoserver catalog: 400, 
```
 having tcpdump -A running locally, i see this for the PUT call (note the zero Content-length ? and yes, there are several proxies in between, but geoserver-shell is able to put stuff on the REST API so it works):
```
PUT /geoserver/rest/workspaces/geor/datastores/automated_tests/featuretypes/public_layer.xml HTTP/1.1
x-forwarded-host: georchestra.dev.craig.fr, georchestra.dev.craig.fr
x-forwarded-proto: https
x-real-ip: 172.20.85.109
x-forwarded-for: 172.20.85.109, 10.0.0.1
x-forwarded-port: 443
user-agent: python-requests/2.18.4
accept-encoding: gzip, deflate
accept: application/xml
x-forwarded-server: georchestra.dev.craig.fr
connection: Keep-Alive
sec-proxy: true
Cookie:
sec-username: testadmin
sec-roles: ROLE_BLAH;ROLE_SUPERUSER;ROLE_USER;ROLE_ADMINISTRATOR;ROLE_EXTRACTORAPP;ROLE_GN_ADMIN
sec-email: <redacted>
sec-firstname: Test
sec-lastname: ADMIN
Host: localhost:8180
Content-Length: 0
```

and the server reply:
```
HTTP/1.1 400
X-Frame-Options: SAMEORIGIN
Content-Length: 0
Date: Wed, 12 Sep 2018 13:29:26 GMT
Connection: close
```

Is there a way to enable logging in the requests python module inside the plugin ?

**Comment by SrNetoChan** [comment]
I cannot replicate this issue. Modifying any of a layer's values worked as expected without any warnings or errors.

**Comment by pvgenuchten** [comment]
> It seems there's a `qgis3` branch in the repo with recent commits, cf https://github.com/boundlessgeo/qgis-geoserver-plugin/tree/qgis3 .. so there is hope :)

note that qgis3 branch is now called 'master' (readme.md is not updated)

**Comment by EmilBraunstein** [comment]
Does anyone know a status on making the plugin compatible with QGIS 3? 

Thanks.

**Comment by luipir** [comment]
> Does anyone know a status on making the plugin compatible with QGIS 3?

did you eread https://github.com/boundlessgeo/qgis-geoserver-plugin/issues/89#issuecomment-479532686 ?

**Comment by EmilBraunstein** [comment]
Yes I did. Sorry, being a rookie this does not give me much overview. I’m curious to whether there is an update going on towards QGIS 3? But based on #89, qgis 3 being the ‘master’, I guess that’s the answer.

Thanks.

**Comment by ludwa6** [comment]
> > It seems there's a `qgis3` branch in the repo with recent commits, cf https://github.com/boundlessgeo/qgis-geoserver-plugin/tree/qgis3 .. so there is hope :)
> 
> note that qgis3 branch is now called 'master' (readme.md is not updated)

The link to that branch is broken, FYI.

**Comment by ludwa6** [comment]
So: given that last commit is >2 years ago, i have to ask: is there any movement toward making this plugin compatible w/ QGIS v.3.x?  Or is does this plugin and its repo serve only for users of v.2.x?  In either case, perhaps readme.md should reflect the fact?

**Comment by luipir** [comment]
> So: given that last commit is >2 years ago, i have to ask: is there any movement toward making this plugin compatible w/ QGIS v.3.x? Or is does this plugin and its repo serve only for users of v.2.x? In either case, perhaps readme.md should reflect the fact?

try with the plugin evolution by Geocat https://plugins.qgis.org/plugins/geocatbridge/
This plugin has been abandoned (welll the code is here and feel free to adapt to 3.x or hire a dev to do this) but probably you are looking for Geocat bridge
